### ISSUE TITLE
Unite test "test-backend-ops" crashed on MacOS

### ISSUE THREAD

**Issue by nguoithichkhampha** [ggerganov/llama.cpp#4672]
I'm using MacOS 13.6 (Intel chip). Here is stack trace
![Screenshot 2023-12-29 at 12 16 00 AM](https://github.com/ggerganov/llama.cpp/assets/1573602/cce7c73b-d392-4abc-b9d2-55d172f047f0)

**Comment by slaren** [comment]
There is a lot of missing output that would hint at the issue. I assume this is because the buffer allocation failed. I will add more checks so that these cases are detected and reported instead of crashing, but actually fixing this would require someone with an intel mac to figure what is the issue.

**Comment by nguoithichkhampha** [comment]
[LastTest.log](https://github.com/ggerganov/llama.cpp/files/13812061/LastTest.log)
@slaren , I have uploaded log file when run ctest in verbose mode.
and you are right, seems there is an issue when alloc buffer
`MOE(n_experts=8,n_experts_per_tok=2,n_tokens=1,n_embd=4096,n_ff=8192): ggml_backend_metal_buffer_type_alloc_buffer: error: failed to allocate buffer, size =  3072.58 MiB`

**Comment by slaren** [comment]
Thank you. The out of memory issue in the MoE test is not really a concern, it requires a larger buffer than can be allocated in your system. The log also shows that many `MUL_MAT` and `MUL_MAT_ID` tests are failing, and that's a problem since it may cause the Metal backend to produce wrong results silently. I think there are already some checks for the GPU family in the metal matrix multiplication, but it may not be enough.

**Comment by nguoithichkhampha** [comment]
so, to debug this issue. I should look at the first time failed of MUL_MAT ?
`MUL_MAT(type_a=f32,type_b=f32,m=16,n=1,k=256,bs=[1,1],nr=[1,1]): ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     0.04 MiB, (   17.11 /  1536.00)
19: [MUL_MAT] NMSE = 3.110048 FAIL`

**Comment by slaren** [comment]
All the failed `MUL_MAT` tests are important, not just the first one.

**Comment by ggerganov** [comment]
@nguoithichkhampha Please checkout #4794 and try again:

```bash
make clean
make -j tests && ./tests/test-backend-ops -b Metal
```

If the matrix multiplication tests continue to fail, please run the following and post the output:

```bash
MTL_DEBUG_LAYER=1 ./bin/test-backend-ops
```

**Comment by nguoithichkhampha** [comment]
I see no more test failed but still getting the crash
[test-metal-backend.txt](https://github.com/ggerganov/llama.cpp/files/13853010/test-metal-backend.txt)

**Comment by nguoithichkhampha** [comment]
I think this is make sense when my gpu only `1536 MB VRAM`.
So, we should check [max buffer length](https://developer.apple.com/documentation/metal/mtldevice/2966563-maxbufferlength?language=objc) before call 
`ctx->buffers[0].metal = [device newBufferWithBytesNoCopy:ctx->all_data
                    length:size_aligned
                    options:MTLResourceStorageModeShared
                    deallocator:nil];`
in function `ggml_backend_metal_buffer_type_alloc_buffer`

**Comment by ggerganov** [comment]
Yes, the MOE test is expected to fail due to out of memory - that's not a big concern.
The main problem is that your GPU should support the Metal3 feature set as define by Apple's documentation:

https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

However, we currently fail to detect that:

```py
Backend 2/2 (Metal)
ggml_metal_init: allocating
2024-01-07 17:36:34.077 test-backend-ops[2294:105408] Metal API Validation Enabled
ggml_metal_init: found device: Intel(R) Iris(TM) Plus Graphics 650
ggml_metal_init: picking default device: Intel(R) Iris(TM) Plus Graphics 650
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/Users/Emotiv/llama.cpp/build/bin/ggml-metal.metal'
ggml_metal_init: GPU name:   Intel(R) Iris(TM) Plus Graphics 650
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: simdgroup reduction support   = false
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  =  1610.61 MB
ggml_metal_init: maxTransferRate               = built-in GPU
```

There should be a log message stating:

```py
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
```

I just pushed another change to #4794 that would hopefully fix this.

**Comment by nguoithichkhampha** [comment]
tried with latest commit. I see the message `GPU family: MTLGPUFamilyMetal3` as the expectation but seems get another error and then an assertion
```
ggml_metal_init: found device: Intel(R) Iris(TM) Plus Graphics 650
ggml_metal_init: picking default device: Intel(R) Iris(TM) Plus Graphics 650
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/Users/Emotiv/llama.cpp/build/bin/ggml-metal.metal'
ggml_metal_init: GPU name:   Intel(R) Iris(TM) Plus Graphics 650
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  =  1610.61 MB
ggml_metal_init: maxTransferRate               = built-in GPU
ggml_metal_init: error: load pipeline error: Error Domain=CompilerError Code=2 "AIR builtin function was called but no definition was found." UserInfo={NSLocalizedDescription=AIR builtin function was called but no definition was found.}
GGML_ASSERT: /Users/Emotiv/llama.cpp/tests/test-backend-ops.cpp:1703: backend != NULL
```

**Comment by ggerganov** [comment]
Thanks! I think it should work now. When you get the chance - please give it another try with the latest version and if it fails, post the output again. It will be more verbose now

**Comment by nguoithichkhampha** [comment]
ok, I read your code change. seems that my gpu does not support mul_mat.
But it still crashing and seems back to first issue
[output.txt](https://github.com/ggerganov/llama.cpp/files/13854231/output.txt)

**Comment by ggerganov** [comment]
Yup, it is unexpected that the `MUL_MAT` tests fail. Even though SIMD matrix multiplications are not available, it fallbacks to the other kernels which only use SIMD reductions - these should be supported and should work correctly. Not sure what is the issue in this case
