### ISSUE TITLE
The model began to add </s > to each main and server response

### ISSUE THREAD

**Issue by slavonnet** [ggerganov/llama.cpp#6872]
git revision from master 3fec68be4e9577fc53158366d3b3af039c17bb1f

usage cmd lines 
```bash
./server -ngl 16000 --numa numactl --model models/MOE/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf --slots-endpoint-disable -c 4096
```

``` bash
./main --color --threads 8 \
       --file $1 \
       -m models/7B/saiga_mistral-q8_0.gguf \
       --reverse-prompt "### Instruction:\n" \
       --in-prefix "###RESPONCE:" \
       --batch_size 512 --ctx_size 16384 -n -1 \
       --keep -1 \
       --numa numactl \
       --repeat_last_n 64 --repeat_penalty 1.3 \
       -ngl 1048576 \
       --n_predict -2 --temp 0.1 --top_k 260 --top_p 0.98 -s 5

```

`</s>` appeared in all responses.

**Comment by ggerganov** [comment]
Fixed in #6860

**Comment by MB7979** [comment]
I'm still getting stop tokens printed at the end of outputs using main.

**Comment by ggerganov** [comment]
These are currently disabled only in `server`. `main` still renders them
