### ISSUE TITLE
Bug: llama.cpp binaries are compiled dynamically and the library is missing!

### ISSUE THREAD

**Issue by 0wwafa** [ggerganov/llama.cpp#8161]
### What happened?

$ ./build/bin/llama-quantize -h
./build/bin/llama-quantize: error while loading shared libraries: libllama.so: cannot open shared object file: No such file or directory

### Name and Version

latest

### Relevant log output

```shell
see up.
```

**Comment by 0wwafa** [comment]
> Confirmed. #8006 breaks the github release builds.

bug still present.

**Comment by slaren** [comment]
Fixed in #8170

**Comment by hackey** [comment]
> Fixed in #8170

I still get an error after building. I checked 10 minutes ago.

**Comment by SignalRT** [comment]
@slaren It seems that the problem remains in MacOS (at least). I'm not able to build the dynamic link libraries.

**Comment by slaren** [comment]
The macOS releases are no longer built with dynamic libraries. If you are experiencing a different problem, please open a new issue and explain it in detail.

**Comment by splitpierre** [comment]
I'm having the **libllama.so** missing while trying to build and run the [llama-server-**vulkan**.Dockerfile](https://github.com/ggerganov/llama.cpp/blob/b3356/.devops/llama-server-vulkan.Dockerfile) image on **Linux**.
Currently using vulkan in earlier tag b2288. 😞

**Comment by pritam-dey3** [comment]
> I'm having the **libllama.so** missing while trying to build and run the [llama-server-**vulkan**.Dockerfile](https://github.com/ggerganov/llama.cpp/blob/b3356/.devops/llama-server-vulkan.Dockerfile) image on **Linux**. Currently using vulkan in earlier tag b2288. 😞

I can confirm this. I am getting the same error.
`/llama-server: error while loading shared libraries: libllama.so: cannot open shared object file: No such file or directory`

**Comment by bensuperpc** [comment]
Same where:

Commands used:

```
cmake -B build -S . -G Ninja
cmake --build build --config Release
./build/bin/llama-cli
```
Result:

> bensuperpc@raspberrypi:~/dockcross/llama.cpp $ ./build/bin/llama-cli -v
> ./build/bin/llama-cli: error while loading shared libraries: libllama.so: cannot open shared object file: No such file or directory
